name: Prepare
steps:
  - name: Checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 0

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 18
      cache: yarn

  - name: Install Dependencies
    run: yarn --immutable
