import Head from 'next/head';
import { trpc } from '../utils/trpc';

export default function Home() {
  const { data } = trpc.hello.useQuery();
  return (
    <>
      <Head>
        <title>Create Chris App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        Hello from Next Web App!!
        <p>{data}</p>
      </main>
    </>
  );
}
