name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - '!apps/mobile/**'

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: yarn
      
      - name: Install Dependencies
        run: yarn --immutable

  web-app:
    name: Web App
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Build
        run: yarn web:build

  client-package:
    name: Client Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Test
        run: yarn client:test

  server-package:
    name: Server Package
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Test
        run: yarn server:test

  tools:
    name: Tools
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Lint
        run: yarn lint
      - name: Format
        run: yarn format
