name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    paths: ["apps/web/**", "packages/**"]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_PUBLIC_VERCEL_URL: ${{ secrets.NEXT_PUBLIC_VERCEL_URL }}
  LOCAL_URL: ${{ secrets.LOCAL_URL }}

jobs:
  avoid_redundancy:
    name: Avoid Redundancy
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  code-quality:
    name: Code Quality
    runs-on: ubuntu-22.04
    steps:
      - name: Prepare
        uses: ./.github/workflow-templates/prepare.yaml

      - name: Lint
        run: yarn lint

  client-package:
    name: Client Package
    runs-on: ubuntu-22.04
    needs: [code-quality]
    steps:
      - name: Prepare
        uses: ./.github/workflow-templates/prepare.yaml

      - name: Test
        run: yarn client:test

  server-package:
    name: Server Package
    runs-on: ubuntu-22.04
    needs: [code-quality]
    steps:
      - name: Prepare
        uses: ./.github/workflow-templates/prepare.yaml

      - name: Test
        run: yarn server:test

  web-app:
    name: Web App
    runs-on: ubuntu-22.04
    needs: [client-package, server-package]
    steps:
      - name: Prepare
        uses: ./.github/workflow-templates/prepare.yaml

      - name: Build
        run: yarn web:build
